version: "3.7"
services:
  api:
    build:
      context: .
      target: workspace
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/dist"
      - "/usr/src/app/node_modules"