name: CI
on: [push]
env:
  WORKING_DIRECTORY: 52aa6377acf1-firestore-converter

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          yarn install
          yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          yarn install
          yarn build
